### ISSUE TITLE
Pass more information from generator to photoMosaicActivity

### ISSUE THREAD

**Issue by mkalish** [mkalish/AndroidMosaic#13]
Specifically, the number of bitmaps per row, and the size of the bitmaps used to generate the mosaic.

**Comment by mopierotti** [comment]
@mkalish 
I added getNumTilesPerRowInSolution(), getNumTilesPerColumnInSolution(), and getWidthOfTileInPixels() to the generator.  Note that a target image needs to be set first in order to call these.  Also the height of a tile is the same as the width because they're squares.

Also note that the width that the third method returns is just how much of the target image a given AnalyzedImage/Tile/Bitmap maps to.  I don't think this is necessary to render a solution.

I think to render the solution you'd first decide how big you wanted the end result to be.  Then to render the rows, divide the width you decided by the number of tiles per row, then for each AnalyzedImage fetch the source bitmap and apply the same cropping that the preprocessor did to it (yet to be exposed) and scale it to the size you just calculated.

Yes I do like verbose method names.
