### ISSUE TITLE
Save bitmaps to disc rather than in Context

### ISSUE THREAD

**Issue by mkalish** [mkalish/AndroidMosaic#6]

**Comment by mkalish** [comment]
-Added changes are saved to disk
-Changed so after a bitmap is processed it is erased from the application context

**Comment by mkalish** [comment]
Is there a graceful way for the preprocessor to delete each bitmap it processes?

**Comment by mopierotti** [comment]
Why do you want to delete the bitmap?  Not saying you're wrong or anything, I just don't understand.

**Comment by mkalish** [comment]
I thought the reason we wanted to save the bitmaps to disc was to take them out of memory and then just access them by file path.

**Comment by mopierotti** [comment]
Oh, so you mean to release the memory?  The preprocessor probably shouldn't be responsible for destroying the bitmaps because it's not creating them.

Anyway, reading the documentation for Bitmap.recycle(), it looks like we don't need to worry about it as long as we don't hold references to them.

Edit: And the preprocessor does not hold onto references.

**Comment by mkalish** [comment]
sweet, sounds good, I'm closing this then
